# Change these first
owner: HervormdPutten # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: HervormdPutten
    url: https://www.hervormdputten.nl
  - name: Toezeggingen 
    url: https://toezeggingen.hervormdputten.nl
  - name: Check 
    url: https://check.hervormdputten.nl
    icon: https://check.hervormdputten.nl/static/favicon.ico

status-website:
  baseUrl: /status
  name: Status
  logoUrl: https://raw.githubusercontent.com/HervormdPutten/status/master/assets/Hervormd_Putten_logo_RGB.png
  favicon: https://check.hervormdputten.nl/static/favicon.ico
  introTitle: "Status page of websites of the Hervomde Gemeente Putten"
  introMessage: Github and Github actions are used to make this available, [see Github](https://github.com/HervormdPutten/status)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - cbos
  
commitMessages:
  commitAuthorName: "HGP Bot"
  commitAuthorEmail: "hgpbot@hervormdputten.nl"
  readmeContent: "Update summary in README [skip ci]"
  summaryJson: "Update status summary [skip ci]"
  statusChange: "Status $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: "Update graphs [skip ci]"
