# Change these first
owner: HervormdPutten # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: HervormdPutten
    url: https://www.hervormdputten.nl
  - name: Toezeggingen 
    url: https://toezeggingen.hervormdputten.nl
  - name: Check 
    url: https://check.hervormdputten.nl

status-website:
  baseUrl: /status # where "repo" is your repository name
  name: Status
  logoUrl: https://raw.githubusercontent.com/HervormdPutten/status/master/assets/Hervormd_Putten_logo_RGB.png
  introTitle: "Status page of websites of the Hervomde Gemeente Putten"
  introMessage: Github and Github actions are used to make this available, [see Github](https://github.com/HervormdPutten/status)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
